# Site Settings
title: Capital Technology Services
baseurl: "" # the subpath of your site, e.g. /blog/
description: >
  Capital Technology Services specializes in web application development in Ruby
  and PHP. The company has development staff based in Philadelphia, PA and
  Nashville, TN.
email: sales@cts-llc.net
telephone: '(615) 250-2449'
faxNumber: '(615) 250-2489'
language: en
naics: '541511'
priceRange: '$$'
url: "http://www.cts-llc.net" # the base hostname & protocol for your site
# Social Media
facebook_company_name: capitaltechnologyservices
github_username: capitaltechnologyservices
linkedin_company_name: 334808
twitter_username: capitaltech
# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
whitelist:
  - jekyll-redirect-from
