# Site settings
title: Capital Technology Services
email: support@cts-llc.net
description: > # this means to ignore newlines until "baseurl:"
  Software Development and Consulting
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.cts-llc.net" # the base hostname & protocol for your site
twitter_username:
github_username: capitaltechnologyservices

# Build settings
markdown: kramdown
